"""Add description to MeetingRoom

Revision ID: 3b96cb65c7ce
Revises: a973b6ca0eeb
Create Date: 2023-01-07 03:34:37.527798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b96cb65c7ce'
down_revision = 'a973b6ca0eeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
